package: 
  name: lsst_pwr_ctrl_core
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
   number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
   build:
     - python
     - rogue
     - git
     - gitpython
     - numpy

   run:
     - python
     - rogue
     - numpy

about:
   home: https://github.com/slaclab/lsst-pwr-ctrl-core
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: LSST Power Controller Core Library

